# Generated by Django 5.2.9 on 2026-04-28 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='linked_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('shopkeeper', 'email'), name='unique_customer_email_per_shopkeeper'),
        ),
    ]
